disabled_rules: # rule identifiers to exclude from running
  - colon
  - conditional_returns_on_newline
  - file_length
  - function_body_length
  - function_parameter_count
  - line_length
  - mark
  - nimble_operator
  - switch_case_on_newline
  - todo
  - type_body_length
  - type_name
  - class_delegate_protocol
  - file_header
  - large_tuple
  - prohibited_super_call
  - sorted_imports
  - vertical_parameter_alignment
  - overridden_super_call
  - private_outlet
  - cyclomatic_complexity
opt_in_rules: # some rules are only opt-in
  - empty_count
  - attributes
  - closure_end_indentation
  - closure_spacing
  - explicit_init
  - first_where
  - force_unwrapping
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - redundant_nil_coalescing
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - "DisplayPlanStats"
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - .idea
  - .git
  - "DisplayPlanStatsTests"
  - Pods
  - "DisplayPlanStatsUITests"

identifier_name:
  excluded:
    - id
    - x
    - y

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try: warning # explicitly
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
